from __future__ import annotations

from .families import FamilySpec


# These families are held out from H1-H6 and R2-A. R2-B uses them to make
# family-disjoint evaluation a literal catalog split.
R2B_FAMILIES: tuple[FamilySpec, ...] = (
    FamilySpec(
        "appointments",
        "schedule_service_appointment",
        ("search_service_appointments", "reschedule_service_appointment", "cancel_service_appointment"),
        ("client", "date", "time", "service", "channel"),
        ("notes", "reminder"),
        "channel",
        ("onsite", "phone", "video", "home_visit"),
        "Schedule a {service} appointment for {client} on {date} at {time} via {channel}.",
        "date",
        "What should I consider when choosing an appointment time?",
    ),
    FamilySpec(
        "payments",
        "initiate_vendor_payment",
        ("search_vendor_payments", "cancel_vendor_payment", "refund_vendor_payment"),
        ("payee", "amount", "currency", "reference", "method"),
        ("memo", "scheduled_date"),
        "method",
        ("bank_transfer", "card", "direct_debit", "wire"),
        "Pay {payee} {amount} {currency} by {method} using reference {reference}.",
        "payee",
        "Explain the difference between a bank transfer and a card payment.",
    ),
    FamilySpec(
        "inventory",
        "reserve_inventory_item",
        ("search_inventory_items", "release_inventory_item", "transfer_inventory_item"),
        ("sku", "quantity", "warehouse", "priority", "expires_at"),
        ("requester", "note"),
        "priority",
        ("routine", "normal", "high", "critical"),
        "Reserve {quantity} units of {sku} at {warehouse} with {priority} priority until {expires_at}.",
        "sku",
        "Why do warehouses use stock keeping units?",
    ),
    FamilySpec(
        "team_messaging",
        "send_team_message",
        ("search_team_messages", "delete_team_message", "schedule_team_message"),
        ("workspace", "recipient", "message", "urgency", "send_at"),
        ("thread", "attachment"),
        "urgency",
        ("low", "normal", "high", "urgent"),
        "Send {recipient} in {workspace} a {urgency} message at {send_at}: {message}.",
        "recipient",
        "What makes a team message easy to act on?",
    ),
    FamilySpec(
        "tasks",
        "create_project_task",
        ("search_project_tasks", "update_project_task", "complete_project_task"),
        ("title", "due_date", "assignee", "priority", "project"),
        ("description", "labels"),
        "priority",
        ("low", "medium", "high", "urgent"),
        "Create task {title} in {project}, assign it to {assignee}, set {priority} priority, and make it due {due_date}.",
        "assignee",
        "How should a large project be divided into tasks?",
    ),
    FamilySpec(
        "health_logging",
        "log_health_measurement",
        ("search_health_measurements", "delete_health_measurement", "summarize_health_measurements"),
        ("measurement", "value", "unit", "timestamp", "source"),
        ("note", "device_id"),
        "source",
        ("manual", "wearable", "clinic", "home_device"),
        "Log {measurement} as {value} {unit} at {timestamp} from {source}.",
        "value",
        "Why can measurements vary between devices?",
    ),
    FamilySpec(
        "media",
        "create_media_playlist",
        ("search_media_playlists", "update_media_playlist", "delete_media_playlist"),
        ("name", "genre", "visibility", "tracks", "owner"),
        ("description", "collaborative"),
        "visibility",
        ("private", "shared", "public", "unlisted"),
        "Create a {visibility} {genre} playlist named {name} for {owner} with tracks {tracks}.",
        "tracks",
        "How do people usually organize a music collection?",
    ),
    FamilySpec(
        "logistics",
        "schedule_package_delivery",
        ("track_package_delivery", "cancel_package_delivery", "reschedule_package_delivery"),
        ("origin", "destination", "package_id", "delivery_date", "service"),
        ("instructions", "insurance"),
        "service",
        ("economy", "standard", "express", "same_day"),
        "Schedule package {package_id} from {origin} to {destination} for {delivery_date} using {service} service.",
        "destination",
        "What factors affect package delivery time?",
    ),
)
