from __future__ import annotations

from .families import FamilySpec


R2C_PILOT_FAMILIES: tuple[FamilySpec, ...] = (
    FamilySpec(
        "expense_claims",
        "submit_expense_claim",
        ("search_expense_claims", "approve_expense_claim", "cancel_expense_claim"),
        ("employee_id", "amount", "currency", "category", "receipt_id"),
        ("note", "cost_center"),
        "category",
        ("travel", "meals", "lodging", "supplies"),
        "Submit an expense claim for {employee_id}: {amount} {currency}, category {category}, receipt {receipt_id}.",
        "receipt_id",
        "How do organizations usually review expense claims?",
    ),
    FamilySpec(
        "access_grants",
        "grant_workspace_access",
        ("search_workspace_access", "revoke_workspace_access", "request_workspace_access"),
        ("workspace", "user_id", "role", "expires_at", "reason_code"),
        ("note", "approver"),
        "role",
        ("viewer", "editor", "admin", "auditor"),
        "Grant {user_id} {role} access to {workspace} until {expires_at} for reason {reason_code}.",
        "user_id",
        "Why should workspace access be reviewed periodically?",
    ),
)

R2C_CONFIRM_FAMILIES: tuple[FamilySpec, ...] = (
    FamilySpec(
        "event_tickets",
        "purchase_event_tickets",
        ("search_event_tickets", "refund_event_tickets", "transfer_event_tickets"),
        ("event_id", "attendee", "quantity", "ticket_class", "delivery_email"),
        ("promotion_code", "accessibility_note"),
        "ticket_class",
        ("standard", "premium", "vip", "balcony"),
        "Purchase {quantity} {ticket_class} tickets for {event_id} for {attendee}, delivered to {delivery_email}.",
        "delivery_email",
        "What affects the price of tickets for a live event?",
    ),
    FamilySpec(
        "cloud_backups",
        "create_cloud_backup",
        ("search_cloud_backups", "restore_cloud_backup", "delete_cloud_backup"),
        ("resource_id", "region", "retention_days", "snapshot_name", "encryption_key_id"),
        ("description", "tags"),
        "region",
        ("eu_west", "us_east", "ap_south", "eu_central"),
        "Create backup {snapshot_name} for {resource_id} in {region}, retain it for {retention_days} days, using key {encryption_key_id}.",
        "resource_id",
        "Why do backup retention periods differ across systems?",
    ),
    FamilySpec(
        "purchase_orders",
        "submit_purchase_order",
        ("search_purchase_orders", "approve_purchase_order", "cancel_purchase_order"),
        ("supplier_id", "item_code", "quantity", "currency", "delivery_date"),
        ("memo", "department"),
        "currency",
        ("GBP", "EUR", "USD", "CAD"),
        "Submit a purchase order to {supplier_id} for {quantity} units of {item_code} in {currency}, due {delivery_date}.",
        "supplier_id",
        "What information normally appears on a purchase order?",
    ),
    FamilySpec(
        "rail_travel",
        "book_rail_trip",
        ("search_rail_trips", "cancel_rail_trip", "change_rail_trip"),
        ("origin", "destination", "travel_date", "service_class", "passenger"),
        ("seat_preference", "railcard"),
        "service_class",
        ("standard", "first", "sleeper", "flexible"),
        "Book {passenger} from {origin} to {destination} on {travel_date} in {service_class} class.",
        "destination",
        "How does flexible rail travel differ from a fixed ticket?",
    ),
    FamilySpec(
        "restaurant_booking",
        "reserve_restaurant_table",
        ("search_restaurant_tables", "cancel_restaurant_table", "change_restaurant_table"),
        ("restaurant", "date", "time", "party_size", "seating"),
        ("occasion", "dietary_note"),
        "seating",
        ("indoor", "outdoor", "bar", "private_room"),
        "Reserve a {seating} table at {restaurant} for {party_size} people on {date} at {time}.",
        "time",
        "What should diners consider when choosing indoor or outdoor seating?",
    ),
    FamilySpec(
        "document_signing",
        "send_document_for_signature",
        ("search_signature_requests", "cancel_signature_request", "remind_document_signer"),
        ("document_id", "signer_email", "due_date", "signature_order", "message_code"),
        ("cc_email", "reminder_days"),
        "signature_order",
        ("parallel", "sequential", "witnessed", "notarized"),
        "Send {document_id} to {signer_email} for {signature_order} signature by {due_date}, using message {message_code}.",
        "signer_email",
        "Why do some documents require signatures in sequence?",
    ),
    FamilySpec(
        "software_deployment",
        "deploy_software_release",
        ("inspect_software_release", "rollback_software_release", "schedule_software_release"),
        ("service", "version", "environment", "region", "change_ticket"),
        ("notes", "approval_id"),
        "environment",
        ("development", "staging", "production", "canary"),
        "Deploy {service} version {version} to {environment} in {region} under ticket {change_ticket}.",
        "change_ticket",
        "What distinguishes a canary deployment from a production rollout?",
    ),
    FamilySpec(
        "equipment_rental",
        "reserve_equipment_rental",
        ("search_equipment_rentals", "cancel_equipment_rental", "extend_equipment_rental"),
        ("equipment_type", "start_date", "end_date", "location", "rental_plan"),
        ("operator", "insurance_note"),
        "rental_plan",
        ("daily", "weekly", "weekend", "long_term"),
        "Reserve a {equipment_type} at {location} from {start_date} to {end_date} on the {rental_plan} plan.",
        "equipment_type",
        "How do weekly and daily equipment rental plans differ?",
    ),
)
