from __future__ import annotations

from .families import FamilySpec


R2D_CONFIRM_FAMILIES: tuple[FamilySpec, ...] = (
    FamilySpec(
        "payroll_adjustments",
        "submit_payroll_adjustment",
        ("search_payroll_adjustments", "approve_payroll_adjustment", "reverse_payroll_adjustment"),
        ("employee_id", "amount", "currency", "category", "reason_code"),
        ("department", "memo"),
        "category",
        ("travel", "meals", "lodging", "supplies"),
        "Apply a {amount} {currency} {category} payroll adjustment to {employee_id} under reason {reason_code}.",
        "employee_id",
        "How do payroll adjustments differ from ordinary salary payments?",
    ),
    FamilySpec(
        "identity_badges",
        "issue_identity_badge",
        ("search_identity_badges", "replace_identity_badge", "update_identity_badge"),
        ("user_id", "workspace", "role", "expires_at", "reason_code"),
        ("department", "notes"),
        "role",
        ("viewer", "editor", "admin", "auditor"),
        "Issue {user_id} a {role} identity badge for {workspace} until {expires_at}, citing {reason_code}.",
        "user_id",
        "Why should identity badges have explicit expiry dates?",
    ),
    FamilySpec(
        "audit_exports",
        "create_audit_export",
        ("search_audit_exports", "inspect_audit_export", "delete_audit_export"),
        ("resource_id", "region", "retention_days", "snapshot_name", "encryption_key_id"),
        ("description", "tags"),
        "region",
        ("eu_west", "us_east", "ap_south", "eu_central"),
        "Create audit export {snapshot_name} for {resource_id} in {region}, retained for {retention_days} days with key {encryption_key_id}.",
        "encryption_key_id",
        "Why are audit exports commonly encrypted and time limited?",
    ),
    FamilySpec(
        "conference_registration",
        "register_conference_attendee",
        ("search_conference_attendees", "update_conference_registration", "transfer_conference_registration"),
        ("event_id", "attendee", "quantity", "ticket_class", "delivery_email"),
        ("promotion_code", "accessibility_note"),
        "ticket_class",
        ("standard", "premium", "vip", "balcony"),
        "Register {attendee} for {quantity} {ticket_class} places at {event_id} and send confirmation to {delivery_email}.",
        "delivery_email",
        "What usually distinguishes standard and premium conference registration?",
    ),
    FamilySpec(
        "freight_transfers",
        "book_freight_transfer",
        ("search_freight_transfers", "track_freight_transfer", "quote_freight_transfer"),
        ("origin", "destination", "travel_date", "service_class", "passenger"),
        ("insurance_note", "reference"),
        "service_class",
        ("standard", "first", "sleeper", "flexible"),
        "Book a {service_class} freight transfer for {passenger} from {origin} to {destination} on {travel_date}.",
        "destination",
        "Why can flexible freight service cost more than standard service?",
    ),
    FamilySpec(
        "venue_spaces",
        "book_venue_space",
        ("search_venue_spaces", "change_venue_booking", "inspect_venue_availability"),
        ("restaurant", "date", "time", "party_size", "seating"),
        ("occasion", "dietary_note"),
        "seating",
        ("indoor", "outdoor", "bar", "private_room"),
        "Book the {seating} space at {restaurant} for {party_size} people on {date} at {time}.",
        "time",
        "What factors matter when choosing an indoor or outdoor venue space?",
    ),
    FamilySpec(
        "release_approvals",
        "approve_release_change",
        ("inspect_release_change", "schedule_release_review", "search_release_changes"),
        ("service", "version", "environment", "region", "change_ticket"),
        ("notes", "approval_id"),
        "environment",
        ("development", "staging", "production", "canary"),
        "Approve {service} version {version} for {environment} in {region} under ticket {change_ticket}.",
        "change_ticket",
        "Why are canary releases reviewed differently from full production releases?",
    ),
    FamilySpec(
        "equipment_inspections",
        "schedule_equipment_inspection",
        ("search_equipment_inspections", "extend_equipment_inspection", "view_equipment_status"),
        ("equipment_type", "start_date", "end_date", "location", "rental_plan"),
        ("operator", "insurance_note"),
        "rental_plan",
        ("daily", "weekly", "weekend", "long_term"),
        "Schedule a {rental_plan} inspection of the {equipment_type} at {location} from {start_date} to {end_date}.",
        "equipment_type",
        "How does inspection planning differ for short-term and long-term equipment use?",
    ),
)


R2D_UNSUPPORTED_REQUESTS = {
    "payroll_adjustments": "Permanently delete every payroll record for {employee_id}.",
    "identity_badges": "Revoke every identity credential held by {user_id} across all systems.",
    "audit_exports": "Restore {resource_id} directly from audit export {snapshot_name}.",
    "conference_registration": "Issue a cash refund for every registration under {event_id}.",
    "freight_transfers": "Cancel all freight movements leaving {origin} on {travel_date}.",
    "venue_spaces": "Publish a public review of {restaurant} on every venue directory.",
    "release_approvals": "Roll back {service} version {version} in {environment} immediately.",
    "equipment_inspections": "Purchase a new {equipment_type} for permanent ownership at {location}.",
    "expense_claims": "Delete all expense records associated with {employee_id}.",
    "access_grants": "Revoke every credential for {user_id} across all workspaces.",
}


R2D_MISSING_REQUESTS = {
    "payroll_adjustments": "Apply a {amount} {currency} {category} payroll adjustment under reason {reason_code}.",
    "identity_badges": "Issue a {role} identity badge for {workspace} until {expires_at}, citing {reason_code}.",
    "audit_exports": "Create audit export {snapshot_name} for {resource_id} in {region}, retained for {retention_days} days.",
    "conference_registration": "Register {attendee} for {quantity} {ticket_class} places at {event_id}.",
    "freight_transfers": "Book a {service_class} freight transfer for {passenger} from {origin} on {travel_date}.",
    "venue_spaces": "Book the {seating} space at {restaurant} for {party_size} people on {date}.",
    "release_approvals": "Approve {service} version {version} for {environment} in {region}.",
    "equipment_inspections": "Schedule a {rental_plan} inspection at {location} from {start_date} to {end_date}.",
    "expense_claims": "Submit an expense claim for {employee_id}: {amount} {currency}, category {category}.",
    "access_grants": "Grant {role} access to {workspace} until {expires_at}, citing {reason_code}.",
}
