from __future__ import annotations

from typing import Any

from .families import FamilySpec


R2E_FAMILIES: tuple[FamilySpec, ...] = (
    FamilySpec(
        "clinical_lab_orders",
        "submit_clinical_lab_order",
        ("search_lab_orders", "cancel_lab_order", "review_lab_result"),
        ("patient", "panel", "collection_site", "fasting_required", "order_reference"),
        ("clinical_note", "copy_to"),
        "panel",
        ("cbc", "metabolic", "thyroid", "lipid"),
        "Submit a {panel} lab order for {patient} at {collection_site}, fasting requirement {fasting_required}, reference {order_reference}.",
        "order_reference",
        "Why can fasting requirements differ across laboratory panels?",
    ),
    FamilySpec(
        "customs_clearances",
        "file_customs_clearance",
        ("search_customs_filings", "amend_customs_filing", "track_customs_review"),
        ("shipment_id", "port", "declaration_type", "gross_weight", "broker_reference"),
        ("commodity_note", "contact_email"),
        "declaration_type",
        ("import", "export", "transit", "temporary"),
        "File a {declaration_type} customs clearance for {shipment_id} at {port}, gross weight {gross_weight} kg, broker reference {broker_reference}.",
        "broker_reference",
        "What information is normally reviewed during customs clearance?",
    ),
    FamilySpec(
        "course_enrollments",
        "enroll_course_participant",
        ("search_course_enrollments", "drop_course_participant", "audit_course_capacity"),
        ("learner", "course_id", "term", "credits", "advisor_email"),
        ("accessibility_note", "cohort"),
        "term",
        ("spring", "summer", "autumn", "winter"),
        "Enroll {learner} in {course_id} for the {term} term with {credits} credits and notify {advisor_email}.",
        "advisor_email",
        "Why do course credit loads matter for enrollment planning?",
    ),
    FamilySpec(
        "maintenance_dispatches",
        "dispatch_maintenance_visit",
        ("search_maintenance_visits", "reschedule_maintenance_visit", "inspect_asset_history"),
        ("asset_id", "technician", "site", "urgency", "scheduled_date"),
        ("work_note", "access_contact"),
        "urgency",
        ("routine", "priority", "urgent", "emergency"),
        "Dispatch {technician} to service {asset_id} at {site} on {scheduled_date} with {urgency} urgency.",
        "technician",
        "How should maintenance urgency affect dispatch planning?",
    ),
    FamilySpec(
        "media_ingest_jobs",
        "create_media_ingest_job",
        ("search_media_ingest_jobs", "cancel_media_ingest_job", "inspect_media_asset"),
        ("source_uri", "asset_name", "codec", "checksum", "retention_days"),
        ("rights_note", "tags"),
        "codec",
        ("h264", "hevc", "av1", "prores"),
        "Create a {codec} media ingest job from {source_uri} as {asset_name}, checksum {checksum}, retained for {retention_days} days.",
        "checksum",
        "Why are checksums useful in media ingest pipelines?",
    ),
    FamilySpec(
        "policy_endorsements",
        "submit_policy_endorsement",
        ("search_policy_endorsements", "withdraw_policy_endorsement", "inspect_policy_terms"),
        ("policy_id", "insured", "effective_date", "endorsement_type", "premium_delta"),
        ("underwriter_note", "supporting_document"),
        "endorsement_type",
        ("address_change", "coverage_change", "named_insured", "vehicle_change"),
        "Submit a {endorsement_type} endorsement for {policy_id}, insured {insured}, effective {effective_date}, premium delta {premium_delta}.",
        "insured",
        "Why can a policy endorsement change an insurance premium?",
    ),
    FamilySpec(
        "archive_digitization",
        "schedule_archive_digitization",
        ("search_digitization_jobs", "cancel_digitization_job", "inspect_archive_item"),
        ("collection_id", "volume", "output_format", "page_count", "delivery_email"),
        ("handling_note", "ocr_language"),
        "output_format",
        ("pdfa", "tiff", "jpeg2000", "text_pdf"),
        "Schedule {volume} from {collection_id} for {output_format} digitization, {page_count} pages, delivered to {delivery_email}.",
        "volume",
        "How do archival digitization formats differ in preservation quality?",
    ),
    FamilySpec(
        "meter_service_transfers",
        "transfer_meter_service",
        ("search_meter_accounts", "close_meter_service", "inspect_meter_readings"),
        ("meter_id", "account_holder", "service_site", "start_date", "tariff"),
        ("contact_phone", "access_note"),
        "tariff",
        ("standard", "fixed", "time_of_use", "renewable"),
        "Transfer {meter_id} to {account_holder} at {service_site} from {start_date} on the {tariff} tariff.",
        "account_holder",
        "What distinguishes fixed and time-of-use energy tariffs?",
    ),
)


R2E_UNSUPPORTED_REQUESTS = {
    "clinical_lab_orders": "Cancel the surgical appointment for {patient} before the {panel} panel.",
    "customs_clearances": "Authorize release of {shipment_id} without customs review at {port}.",
    "course_enrollments": "Issue a tuition refund to {learner} for {course_id}.",
    "maintenance_dispatches": "Permanently decommission {asset_id} at {site}.",
    "media_ingest_jobs": "Publish {asset_name} to every public streaming service.",
    "policy_endorsements": "Cancel insurance policy {policy_id} and refund {insured}.",
    "archive_digitization": "Destroy the original {volume} after scanning {collection_id}.",
    "meter_service_transfers": "Disconnect all utility services at {service_site} for {account_holder}.",
}


R2E_MISSING_REQUESTS = {
    "clinical_lab_orders": "Submit a {panel} lab order for {patient} at {collection_site}, fasting requirement {fasting_required}.",
    "customs_clearances": "File a {declaration_type} customs clearance for {shipment_id} at {port}, gross weight {gross_weight} kg.",
    "course_enrollments": "Enroll {learner} in {course_id} for the {term} term with {credits} credits.",
    "maintenance_dispatches": "Service {asset_id} at {site} on {scheduled_date} with {urgency} urgency.",
    "media_ingest_jobs": "Create a {codec} media ingest job from {source_uri} as {asset_name}, retained for {retention_days} days.",
    "policy_endorsements": "Submit a {endorsement_type} endorsement for {policy_id}, effective {effective_date}, premium delta {premium_delta}.",
    "archive_digitization": "Schedule {collection_id} for {output_format} digitization, {page_count} pages, delivered to {delivery_email}.",
    "meter_service_transfers": "Transfer {meter_id} at {service_site} from {start_date} on the {tariff} tariff.",
}


def r2e_values(index: int) -> dict[str, Any]:
    day = index % 24 + 1
    return {
        "patient": f"Patient {12000 + index}",
        "panel": ("cbc", "metabolic", "thyroid", "lipid")[index % 4],
        "collection_site": f"Site {index % 9}",
        "fasting_required": bool(index % 2),
        "order_reference": f"LAB-{22000 + index}",
        "shipment_id": f"SHIP-{32000 + index}",
        "port": f"Port {index % 11}",
        "declaration_type": ("import", "export", "transit", "temporary")[index % 4],
        "gross_weight": float(500 + 2 * index),
        "broker_reference": f"BRK-{42000 + index}",
        "learner": f"Learner {52000 + index}",
        "course_id": f"CRS-{62000 + index}",
        "term": ("spring", "summer", "autumn", "winter")[index % 4],
        "credits": index % 5 + 1,
        "advisor_email": f"advisor{index}@example.edu",
        "asset_id": f"ASSET-{72000 + index}",
        "technician": f"Technician {82000 + index}",
        "site": f"Site {index % 13}",
        "urgency": ("routine", "priority", "urgent", "emergency")[index % 4],
        "scheduled_date": f"2027-02-{day:02d}",
        "source_uri": f"s3://ingest-bucket/media-{92000 + index}.mov",
        "asset_name": f"asset-{102000 + index}",
        "codec": ("h264", "hevc", "av1", "prores")[index % 4],
        "checksum": f"SHA256-{112000 + index}",
        "retention_days": (30, 60, 90, 180)[index % 4],
        "policy_id": f"POL-{122000 + index}",
        "insured": f"Insured {132000 + index}",
        "effective_date": f"2027-03-{day:02d}",
        "endorsement_type": ("address_change", "coverage_change", "named_insured", "vehicle_change")[index % 4],
        "premium_delta": float(10 + index % 50),
        "collection_id": f"COLL-{142000 + index}",
        "volume": f"Volume {152000 + index}",
        "output_format": ("pdfa", "tiff", "jpeg2000", "text_pdf")[index % 4],
        "page_count": 100 + index,
        "delivery_email": f"archive{index}@example.org",
        "meter_id": f"MTR-{162000 + index}",
        "account_holder": f"Holder {172000 + index}",
        "service_site": f"Site {index % 17}",
        "start_date": f"2027-04-{day:02d}",
        "tariff": ("standard", "fixed", "time_of_use", "renewable")[index % 4],
    }
