from __future__ import annotations

from typing import Any

from .families import FamilySpec


R2F_FAMILIES: tuple[FamilySpec, ...] = (
    FamilySpec(
        "pharmacy_refills",
        "schedule_pharmacy_refill",
        ("search_prescriptions", "cancel_refill", "review_medication_history"),
        ("patient", "prescription_id", "pharmacy", "fulfillment", "pickup_date"),
        ("contact_email", "note"),
        "fulfillment",
        ("pickup", "delivery", "locker", "courier"),
        "Schedule {fulfillment} of {prescription_id} for {patient} at {pharmacy} on {pickup_date}.",
        "pharmacy",
        "Why can refill timing differ between prescriptions?",
    ),
    FamilySpec(
        "building_access_badges",
        "activate_building_badge",
        ("search_badges", "suspend_badge", "audit_badge_events"),
        ("employee", "badge_id", "building", "access_level", "activation_date"),
        ("sponsor_email", "access_note"),
        "access_level",
        ("visitor", "standard", "restricted", "after_hours"),
        "Activate {badge_id} for {employee} at {building} with {access_level} access on {activation_date}.",
        "building",
        "How do organizations normally separate physical access levels?",
    ),
    FamilySpec(
        "invoice_payments",
        "submit_invoice_payment",
        ("search_invoices", "void_payment", "inspect_payment_status"),
        ("invoice_id", "payee", "amount", "currency", "payment_date"),
        ("memo", "approval_email"),
        "currency",
        ("usd", "eur", "gbp", "cad"),
        "Pay {amount} {currency} on {invoice_id} to {payee} on {payment_date}.",
        "payment_date",
        "Why do invoice payment dates affect cash-flow reporting?",
    ),
    FamilySpec(
        "crop_inspections",
        "schedule_crop_inspection",
        ("search_crop_inspections", "cancel_crop_inspection", "review_field_history"),
        ("field_id", "inspector", "crop", "acreage", "inspection_date"),
        ("sampling_note", "contact_email"),
        "crop",
        ("wheat", "maize", "soy", "barley"),
        "Schedule {inspector} to inspect {acreage} acres of {crop} at {field_id} on {inspection_date}.",
        "inspector",
        "Why are crop inspections scheduled at different growth stages?",
    ),
    FamilySpec(
        "vehicle_registrations",
        "renew_vehicle_registration",
        ("search_vehicle_records", "cancel_registration", "inspect_registration_status"),
        ("vehicle_id", "owner", "jurisdiction", "registration_class", "expiry_date"),
        ("contact_email", "note"),
        "registration_class",
        ("private", "commercial", "historic", "temporary"),
        "Renew {vehicle_id} for {owner} in {jurisdiction} as {registration_class} through {expiry_date}.",
        "owner",
        "Why do vehicle registration classes have different requirements?",
    ),
    FamilySpec(
        "grant_disbursements",
        "release_grant_disbursement",
        ("search_grants", "hold_disbursement", "inspect_grant_balance"),
        ("grant_id", "recipient", "amount", "tranche", "release_date"),
        ("approval_email", "note"),
        "tranche",
        ("initial", "milestone", "final", "supplemental"),
        "Release the {tranche} disbursement of {amount} for {grant_id} to {recipient} on {release_date}.",
        "recipient",
        "Why are grant funds often released in tranches?",
    ),
    FamilySpec(
        "library_relocations",
        "schedule_library_relocation",
        ("search_library_items", "cancel_relocation", "inspect_item_location"),
        ("item_id", "destination_branch", "carrier", "handling", "move_date"),
        ("shelf_note", "contact_email"),
        "handling",
        ("standard", "fragile", "climate_controlled", "secure"),
        "Move {item_id} to {destination_branch} with {carrier} using {handling} handling on {move_date}.",
        "destination_branch",
        "Why do some library materials require special handling?",
    ),
    FamilySpec(
        "telecom_plan_changes",
        "change_telecom_plan",
        ("search_telecom_accounts", "cancel_plan_change", "inspect_usage"),
        ("account_id", "subscriber", "plan", "effective_date", "contact_email"),
        ("retention_note", "promotion_code"),
        "plan",
        ("basic", "unlimited", "family", "business"),
        "Change {account_id} for {subscriber} to the {plan} plan on {effective_date} and notify {contact_email}.",
        "subscriber",
        "How do mobile data plans usually differ?",
    ),
    FamilySpec(
        "sample_shipments",
        "dispatch_sample_shipment",
        ("search_sample_shipments", "cancel_sample_shipment", "inspect_sample_chain"),
        ("sample_id", "recipient", "destination", "temperature", "package_count"),
        ("tracking_email", "handling_note"),
        "temperature",
        ("ambient", "chilled", "frozen", "cryogenic"),
        "Dispatch {package_count} packages of {sample_id} to {recipient} at {destination} under {temperature} handling.",
        "destination",
        "Why does sample shipping temperature affect specimen quality?",
    ),
    FamilySpec(
        "event_catering_orders",
        "place_catering_order",
        ("search_catering_orders", "cancel_catering_order", "inspect_menu_options"),
        ("event_id", "coordinator", "venue", "service_style", "guest_count"),
        ("dietary_note", "contact_email"),
        "service_style",
        ("buffet", "plated", "reception", "boxed"),
        "Place a {service_style} catering order for {event_id}, coordinated by {coordinator} at {venue}, for {guest_count} guests.",
        "venue",
        "How does catering service style affect event staffing?",
    ),
    FamilySpec(
        "permit_applications",
        "submit_permit_application",
        ("search_permits", "withdraw_permit", "inspect_permit_status"),
        ("parcel_id", "applicant", "permit_type", "fee", "contact_email"),
        ("project_note", "document_uri"),
        "permit_type",
        ("renovation", "demolition", "occupancy", "signage"),
        "Submit a {permit_type} application for {parcel_id} by {applicant}, fee {fee}, contact {contact_email}.",
        "applicant",
        "Why do permit review times differ by project type?",
    ),
    FamilySpec(
        "device_warranty_claims",
        "open_device_warranty_claim",
        ("search_warranty_claims", "close_warranty_claim", "inspect_device_coverage"),
        ("serial_id", "claimant", "issue_code", "remedy", "purchase_date"),
        ("contact_email", "diagnostic_note"),
        "remedy",
        ("repair", "replacement", "refund_review", "parts_only"),
        "Open a {remedy} warranty claim for {serial_id}, claimant {claimant}, issue {issue_code}, purchased {purchase_date}.",
        "claimant",
        "Why can warranty remedies differ for the same product category?",
    ),
    FamilySpec(
        "warehouse_replenishments",
        "create_replenishment_order",
        ("search_inventory", "cancel_replenishment", "inspect_stock_history"),
        ("sku_id", "warehouse", "supplier", "priority", "quantity"),
        ("buyer_email", "receiving_note"),
        "priority",
        ("routine", "expedited", "critical", "seasonal"),
        "Create a {priority} replenishment of {quantity} units of {sku_id} for {warehouse} from {supplier}.",
        "supplier",
        "Why do warehouses use different replenishment priorities?",
    ),
    FamilySpec(
        "manuscript_submissions",
        "submit_manuscript",
        ("search_submissions", "withdraw_manuscript", "inspect_review_status"),
        ("manuscript_id", "corresponding_author", "journal", "article_type", "cover_uri"),
        ("editor_note", "contact_email"),
        "article_type",
        ("research", "review", "methods", "brief_report"),
        "Submit {manuscript_id} from {cover_uri} by {corresponding_author} to {journal} as a {article_type} article.",
        "corresponding_author",
        "Why do journals distinguish manuscript article types?",
    ),
    FamilySpec(
        "solar_interconnections",
        "submit_solar_interconnection",
        ("search_interconnections", "withdraw_interconnection", "inspect_grid_capacity"),
        ("site_id", "applicant", "capacity_kw", "connection_type", "target_date"),
        ("engineer_email", "design_uri"),
        "connection_type",
        ("residential", "commercial", "community", "storage_hybrid"),
        "Submit a {connection_type} interconnection for {site_id}, applicant {applicant}, capacity {capacity_kw} kW, target {target_date}.",
        "applicant",
        "Why does solar interconnection review depend on system capacity?",
    ),
    FamilySpec(
        "volunteer_shift_assignments",
        "assign_volunteer_shift",
        ("search_volunteer_shifts", "cancel_shift_assignment", "inspect_volunteer_hours"),
        ("volunteer", "shift_id", "location", "role", "shift_date"),
        ("coordinator_email", "access_note"),
        "role",
        ("registration", "logistics", "support", "cleanup"),
        "Assign {volunteer} to {shift_id} at {location} in the {role} role on {shift_date}.",
        "volunteer",
        "Why are volunteer roles matched to different shift requirements?",
    ),
)


R2F_UNSUPPORTED_REQUESTS = {
    family.name: template
    for family, template in zip(
        R2F_FAMILIES,
        (
            "Diagnose a new condition for {patient} from {prescription_id}.",
            "Disable every security alarm at {building} for {employee}.",
            "Erase the accounting record for {invoice_id} after paying {payee}.",
            "Authorize pesticide use across {field_id} without an inspection.",
            "Transfer legal ownership of {vehicle_id} away from {owner}.",
            "Rewrite the award terms for {grant_id} without review by {recipient}.",
            "Dispose of {item_id} instead of moving it to {destination_branch}.",
            "Intercept private messages for {account_id} belonging to {subscriber}.",
            "Destroy {sample_id} rather than shipping it to {destination}.",
            "Book the entire {venue} exclusively for {event_id}.",
            "Approve construction on {parcel_id} without review for {applicant}.",
            "Modify the purchase receipt for {serial_id} submitted by {claimant}.",
            "Delete all inventory records for {sku_id} at {warehouse}.",
            "Accept {manuscript_id} for publication without peer review.",
            "Energize {site_id} before technical approval for {applicant}.",
            "Change payroll records for {volunteer} assigned to {shift_id}.",
        ),
        strict=True,
    )
}


R2F_MISSING_REQUESTS = {
    "pharmacy_refills": "Schedule {fulfillment} of {prescription_id} for {patient} on {pickup_date}.",
    "building_access_badges": "Activate {badge_id} for {employee} with {access_level} access on {activation_date}.",
    "invoice_payments": "Pay {amount} {currency} on {invoice_id} to {payee}.",
    "crop_inspections": "Schedule an inspection of {acreage} acres of {crop} at {field_id} on {inspection_date}.",
    "vehicle_registrations": "Renew {vehicle_id} in {jurisdiction} as {registration_class} through {expiry_date}.",
    "grant_disbursements": "Release the {tranche} disbursement of {amount} for {grant_id} on {release_date}.",
    "library_relocations": "Move {item_id} with {carrier} using {handling} handling on {move_date}.",
    "telecom_plan_changes": "Change {account_id} to the {plan} plan on {effective_date} and notify {contact_email}.",
    "sample_shipments": "Dispatch {package_count} packages of {sample_id} to {recipient} under {temperature} handling.",
    "event_catering_orders": "Place a {service_style} catering order for {event_id}, coordinated by {coordinator}, for {guest_count} guests.",
    "permit_applications": "Submit a {permit_type} application for {parcel_id}, fee {fee}, contact {contact_email}.",
    "device_warranty_claims": "Open a {remedy} warranty claim for {serial_id}, issue {issue_code}, purchased {purchase_date}.",
    "warehouse_replenishments": "Create a {priority} replenishment of {quantity} units of {sku_id} for {warehouse}.",
    "manuscript_submissions": "Submit {manuscript_id} from {cover_uri} to {journal} as a {article_type} article.",
    "solar_interconnections": "Submit a {connection_type} interconnection for {site_id}, capacity {capacity_kw} kW, target {target_date}.",
    "volunteer_shift_assignments": "Assign {shift_id} at {location} in the {role} role on {shift_date}.",
}


R2F_SEMANTIC_ENVELOPES = {
    "patient": "head_number",
    "pharmacy": "head_number",
    "employee": "head_number",
    "building": "head_number",
    "payee": "head_number",
    "inspector": "head_number",
    "owner": "head_number",
    "jurisdiction": "head_number",
    "recipient": "head_number",
    "destination_branch": "head_number",
    "carrier": "head_number",
    "subscriber": "head_number",
    "destination": "head_number",
    "coordinator": "head_number",
    "venue": "head_number",
    "applicant": "head_number",
    "claimant": "head_number",
    "warehouse": "head_number",
    "supplier": "head_number",
    "corresponding_author": "head_number",
    "journal": "head_number",
    "volunteer": "head_number",
    "location": "head_number",
    "cover_uri": "uri",
}


def r2f_values(index: int) -> dict[str, Any]:
    day = index % 24 + 1
    return {
        "patient": f"Patient {200000 + index}",
        "prescription_id": f"RX-{210000 + index}",
        "pharmacy": f"Pharmacy {index % 19}",
        "fulfillment": ("pickup", "delivery", "locker", "courier")[index % 4],
        "pickup_date": f"2027-05-{day:02d}",
        "employee": f"Employee {220000 + index}",
        "badge_id": f"BADGE-{230000 + index}",
        "building": f"Building {index % 23}",
        "access_level": ("visitor", "standard", "restricted", "after_hours")[index % 4],
        "activation_date": f"2027-06-{day:02d}",
        "invoice_id": f"INV-{240000 + index}",
        "payee": f"Payee {250000 + index}",
        "amount": float(100 + index % 700),
        "currency": ("usd", "eur", "gbp", "cad")[index % 4],
        "payment_date": f"2027-07-{day:02d}",
        "field_id": f"FIELD-{260000 + index}",
        "inspector": f"Inspector {270000 + index}",
        "crop": ("wheat", "maize", "soy", "barley")[index % 4],
        "acreage": float(10 + index % 90),
        "inspection_date": f"2027-08-{day:02d}",
        "vehicle_id": f"VIN-{280000 + index}",
        "owner": f"Owner {290000 + index}",
        "jurisdiction": f"District {index % 17}",
        "registration_class": ("private", "commercial", "historic", "temporary")[index % 4],
        "expiry_date": f"2028-09-{day:02d}",
        "grant_id": f"GRANT-{300000 + index}",
        "recipient": f"Recipient {310000 + index}",
        "tranche": ("initial", "milestone", "final", "supplemental")[index % 4],
        "release_date": f"2027-10-{day:02d}",
        "item_id": f"ITEM-{320000 + index}",
        "destination_branch": f"Branch {index % 13}",
        "carrier": f"Carrier {index % 11}",
        "handling": ("standard", "fragile", "climate_controlled", "secure")[index % 4],
        "move_date": f"2027-11-{day:02d}",
        "account_id": f"ACCOUNT-{330000 + index}",
        "subscriber": f"Subscriber {340000 + index}",
        "plan": ("basic", "unlimited", "family", "business")[index % 4],
        "effective_date": f"2027-12-{day:02d}",
        "contact_email": f"contact{index}@example.net",
        "sample_id": f"SAMPLE-{350000 + index}",
        "destination": f"Lab {index % 29}",
        "temperature": ("ambient", "chilled", "frozen", "cryogenic")[index % 4],
        "package_count": index % 5 + 1,
        "event_id": f"EVENT-{360000 + index}",
        "coordinator": f"Coordinator {370000 + index}",
        "venue": f"Venue {index % 31}",
        "service_style": ("buffet", "plated", "reception", "boxed")[index % 4],
        "guest_count": 20 + index % 180,
        "parcel_id": f"PARCEL-{380000 + index}",
        "applicant": f"Applicant {390000 + index}",
        "permit_type": ("renovation", "demolition", "occupancy", "signage")[index % 4],
        "fee": float(50 + index % 450),
        "serial_id": f"SERIAL-{400000 + index}",
        "claimant": f"Claimant {410000 + index}",
        "issue_code": f"ISSUE-{index % 37}",
        "remedy": ("repair", "replacement", "refund_review", "parts_only")[index % 4],
        "purchase_date": f"2026-01-{day:02d}",
        "sku_id": f"SKU-{420000 + index}",
        "warehouse": f"Warehouse {index % 17}",
        "supplier": f"Supplier {430000 + index}",
        "priority": ("routine", "expedited", "critical", "seasonal")[index % 4],
        "quantity": 10 + index % 190,
        "manuscript_id": f"MS-{440000 + index}",
        "corresponding_author": f"Author {450000 + index}",
        "journal": f"Journal {index % 13}",
        "article_type": ("research", "review", "methods", "brief_report")[index % 4],
        "cover_uri": f"s3://submission-bucket/cover-{460000 + index}.pdf",
        "site_id": f"SOLAR-{470000 + index}",
        "capacity_kw": float(5 + index % 95),
        "connection_type": ("residential", "commercial", "community", "storage_hybrid")[index % 4],
        "target_date": f"2028-02-{day:02d}",
        "volunteer": f"Volunteer {480000 + index}",
        "shift_id": f"SHIFT-{490000 + index}",
        "location": f"Location {index % 23}",
        "role": ("registration", "logistics", "support", "cleanup")[index % 4],
        "shift_date": f"2028-03-{day:02d}",
    }
